#server configuration
server:
  port: 8080
  servlet:
    context-path: /api

#datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codetech
    username: licenta
    password: licenta
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #multipart configuration
  servlet:
    multipart:
      max-file-size: 3500MB
      max-request-size: 4000MB

#application configuration
application:
  version: @project.version@
  jwt:
    access-token-time: 3600000
    refresh-token-time: 7200000
    secret: secret

#service dependency configuration
service:
  mail:
    base-url: http://localhost:8010/mail
    register-url: /register
  media:
    base-url: http://localhost:8011/media
    folder-url: /folders
    upload-file-url: /folders/{folder}/files
    file-path-variable-url: /folders/{folder}/files/{filename}
    zip-files-url: /folders/{folder}/zip
    folder-path-variable-url: /folders/{folder}

